apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sphara
  name: sphara
  labels:
    app: sphara
spec:
  selector:
    matchLabels:
      app: sphara
  template:
    metadata:
      labels:
        app: sphara
        name: sphara
    spec:
      containers:
        - name: sphara
          image: shubha-intelops/sphara/sphara
          imagePullPolicy: Always
        
          env:
            - name: SERVICE_NAME
              value: "go-app"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "localhost:4317"
            - name: INSECURE_MODE
              value: "true"
        
          ports:
        
        
          - containerPort: 8080
            name: http
        
        
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
        