apiVersion: v1
kind: Service
metadata:
  namespace: sphara
  labels:
    app: sphara
  name: sphara
spec:
  ports:
  
    - protocol: TCP
      port: 8080
      targetPort: 8080
   
   
  selector:
    app: sphara
  type: ClusterIP
