apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: signup
  name: signup
  labels:
    app: signup
spec:
  selector:
    matchLabels:
      app: signup
  template:
    metadata:
      labels:
        app: signup
        name: signup
    spec:
      containers:
        - name: signup
          image: shubha-intelops/sphara/signup
          imagePullPolicy: Always
        
          env:
            - name: SERVICE_NAME
              value: "go-app"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "localhost:4317"
            - name: INSECURE_MODE
              value: "true"
        
          ports:
        
        
          - containerPort: 8080
            name: http
        
        
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
        